# Generated by Django 3.2.3 on 2021-05-25 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210525_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidmodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e5ced7a3-0de3-482e-9932-b20744062e3a'), editable=False),
        ),
    ]
