# Generated by Django 3.2.3 on 2021-05-25 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uuidmodel_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuidmodel',
            name='uid',
        ),
        migrations.AddField(
            model_name='uuidmodel',
            name='UUID',
            field=models.UUIDField(default=uuid.UUID('fbb9ad5e-2b34-4133-b33d-30fde6e75141'), editable=False),
        ),
    ]
