# Generated by Django 3.2.3 on 2021-06-22 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210525_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidmodel',
            name='UUID',
            field=models.UUIDField(default=uuid.UUID('62423167-fbef-41ab-94cf-069654668a12'), editable=False),
        ),
    ]
